---
title: "hw_4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### 4.1
```{r}
data = read.csv('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/rita7798/hw4_Advanced_Bayesian/hw4_caretta.csv')
m <- mean(data$vowel.dur, trim = 0.1)
s <- sd(data$vowel.dur)
m_2 <- mean(filter(data, speaker == 'brs02')$vowel.dur, trim = 0.1)
s_2 <- sd(filter(data, speaker == 'brs02')$vowel.dur)
m_post = weighted.mean(c(m, m_2), c(1/s, 1/s_2))
s_post = (1/s+1/s_2)^(-1)
res <- data.frame(speaker = 'brs02', mean_post = m_post, sd_post = s_post)
res
```

### 4.2
```{r}
m_1 <- mean(filter(data, speaker == 'tt01')$vowel.dur, trim = 0.1)
s_1 <- sd(filter(data, speaker == 'tt01')$vowel.dur)
m_post <- weighted.mean(c(m, m_1), c(1/s, 1/s_1))
s_post <- (1/s+1/s_1)^(-1)
low <- qnorm(.025, m_post, s_post)
up <- qnorm(.975, m_post, s_post)
res2 <- data.frame(speaker = 'tt01', lower = low, upper = up)
res2
```