---
title: "hw_4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ca)
```


### 5.1
```{r}
chairs = read.csv('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/rita7798/hw5_CA_MCA/hw5_chairs.csv')
MCA <- MASS::mca(chairs[,-1:-3])
chairs <- cbind(chairs, MCA$rs)
variables <- as_data_frame(MCA$cs)
variables$var_names <- rownames(MCA$cs)
chairs %>% 
  ggplot(aes(`1`, `2`))+
  geom_point(aes(color = Category))+
  stat_ellipse(aes(color = Category))+
  geom_text(data = variables, aes(`1`, `2`, label = var_names), size = 3)+
  theme_bw()+
  scale_x_continuous(limits = c(-0.02, 0.02))
```


### 5.2
```{r}
'В немецком языке Sessel и Stuhl и описывают два разных предмета (отличаются между собой по ряду признаков), однако местами они могут обладать общими характеристиками (как отдельные категории с некоторыми общими свойствами).'
```


### 5.3
```{r}
colreg <- read.csv('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/rita7798/hw5_CA_MCA/hw5_colreg.csv')
rownames(colreg) <- colreg$colors
ca <- ca(colreg[-5])
colreg_col <- data.frame(ca$colcoord)
colreg_col$rows <- rownames(ca$colcoord)
colreg_row <- data.frame(ca$rowcoord)
colreg_row$rows <- rownames(ca$rowcoord)
colreg_col %>% 
  ggplot(aes(Dim1, Dim2, label = rows))+
  geom_text(color = "purple")+
  geom_text(data = colreg_row, color = "darkgreen")+
  theme_bw()+
  scale_x_continuous(limits = c(-3, 3))
```


### 5.4
```{r}
'Из графика видно, что white используется примерно одинаково во всех стилях; black очень часто встречается в разговорной речи; для прессы характерны red, green и orange; а brown, purple, blue, yellow и pink преимущественно употребляются в художественной литературе; и только gray удален от всех остальных.'
```
